# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
