# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='photo_title',
            new_name='photos',
        ),
    ]
