# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20171211_1630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Picture',
        ),
    ]
